### ISSUE TITLE
怎么解决异步action的呢？

### ISSUE THREAD

**Issue by junjie-lean** [BillJC-Liu/JFReduxTool#1]
大佬，目前您这个工具，用redux-thunk的中间件还是没解决异步action的问题。是否考虑把redux-saga或者redux-promise这种中间件集成到工具里呢？这样的话我可以导出一个await函数，直接action里使用。比方说：
import { getData } from "requestList";

export const  ExampleAction  = async function () {
 let data = await getData();
  return {
     type:"getData",
     data
  }
} 

因为我们是在组件内使用的useDispatch。

**Comment by BillJC-Liu** [comment]
model中的reducers 实际上把redux中的reducer 和 action 概念进行了合并。model中的reducers 就是一个reducer，里面执行this.setState的话就是进行了 action中dispatch。这样开发者不需要再去写action进行dispatch。redux-thunk不是做异步操作的，只是将disptahc做了多的一层封装，延迟执行，使用者在action这层概念上既可以是对象，也可以是function。

**Comment by BillJC-Liu** [comment]
说到异步的话，其实可以使用async await。它是promise和generator的一个语法糖。await这条语句会马上执行，它之下的都是异步任务，放在微任务队列中。返回值是经过Promise进行包装过的值。

**Comment by BillJC-Liu** [comment]
主要目的：
1.不用在写switch case进行匹配
2.不用再写多余的action进行一个重复操作
3.不用再写 const TYPE = ”TYPE“ 唯一值
4.简化了dispatch的操作，resetState API简化了初始值的操作，getModelState 简化了获取当前reducer中的状态
5.结构美观，方便查看，降低维护成本
